# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
array1 = np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
print(array1.size,array1.itemsize)
print("%d byte" % (array1.size*array1.itemsize))

10 8
80 byte


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
array2 = np.zeros(10)
array2[4] = 1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array3 = np.arange(start = 10, stop=50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array3_desc = np.sort(array3)[::-1]
print(array3_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a = np.arange(0,9)
am = a.reshape(3,3)
print(am)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
non = np.array([1,2,0,0,4,0])
non1 = non[non!=0]
print(non1)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array1 = np.random.random((3,3,3))
print(array1)

[[[0.16497275 0.41851763 0.98970098]
  [0.84663762 0.03327025 0.08352547]
  [0.01435145 0.0145522  0.76348241]]

 [[0.05967837 0.3554779  0.87005083]
  [0.95230976 0.51497276 0.04276357]
  [0.29863996 0.15440445 0.20229477]]

 [[0.33353745 0.01669426 0.66376793]
  [0.10100951 0.59442696 0.45318798]
  [0.3698065  0.33783916 0.44516501]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array1 = np.random.random((10,10))
Min = array1.min()
Max = array1.max()
print(Min,Max)
print(np.min(array1),np.max(array1))

0.0039982444179398335 0.9757457458713823
0.0039982444179398335 0.9757457458713823


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array1 = np.random.random(30)
print(np.mean(array1))

0.4243546511925546


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array1 = np.ones((10,10))
array1[1:-1,1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array1 = np.zeros((5,5))
for i in range(5):
  for j in range(5):
    if(i-j)==1:
      array1[i][j] = i
print(array1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array1 = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i+j)%2 == 0:
      array1[i][j] = 1
print(array1)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
array1 = np.unravel_index(99,(6,7,8))
print(array1)

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array1 = np.random.random((5,5))
M = array1.mean()
S = array1.std()
Z = (array1-M) / S
print(Z)

[[-0.05096601  0.27846777  0.93876947  0.91594302  0.65866956]
 [-0.70382707 -0.51383754 -1.72166083  0.08823397  0.74121819]
 [ 1.4139632  -1.52338365  0.75582846 -1.34292987 -0.03989302]
 [-0.02452634  1.44316024  0.7671525  -1.63839858 -1.07766492]
 [ 1.06081909  0.07462338 -0.37688914 -1.47400446  1.35113259]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color_dtype = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])
color_dtype

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np

matrix1 = np.random.random((5, 3))  # 5x3 행렬
matrix2 = np.random.random((3, 2))  # 3x2 행렬
product = np.dot(matrix1, matrix2)

print(product)

[[0.4769092  0.76840954]
 [0.70198067 0.87495881]
 [0.90055325 0.71954752]
 [0.56828354 0.58551515]
 [0.9588831  0.85481268]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z<Z>Z 이 파이썬에서 사용될 수 없는 표현식이다.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-21-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-21-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-21-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [18]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1[Z1==Z2])

[6 0 7 6 9 6 3 3 4 9]
[0 5 9 6 7 0 0 2 7 6]
[6]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [103]:
# 주어진 문장의 결과는 false이다.
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-103-a9aa958e369d>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

np.emath() 함수는 음수를 대입했을 때 양수로 바꾼 후 계산하기 때문에,
np.sqrt(-1)의 출력값은 nan이고 np.emath.sqrt(-1)의 출력값은 1이다.

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [19]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [102]:
A = np.array([1, 2, 3], dtype=np.float64)
B = np.array([4, 5, 6], dtype=np.float64)
np.add(A, B, out=A)
np.divide(A, -2, out=B)
np.multiply(A, B, out=A)
print(A)

[-12.5 -24.5 -40.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [59]:
num = np.random.uniform(1, 10, size=10) # random array of positive numbers

# first method
integer1 = num - num%1
print(integer1)

# second method
integer2 = num//1
print(integer2)

[8. 4. 5. 2. 5. 5. 9. 7. 5. 2.]
[8. 4. 5. 2. 5. 5. 9. 7. 5. 2.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
mat = np.array([np.arange(0, 5) for _ in range(5)])
print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [26]:
np.sort(np.random.random(10))

array([0.18768728, 0.3251708 , 0.46783995, 0.53379282, 0.59294463,
       0.59698425, 0.82138434, 0.82382365, 0.83515838, 0.97994768])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [32]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [73]:
# 10x2 random cartesian coordinates
cartesian_coords = np.random.random((10, 2))

# x, y 좌표
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

# convert into polar coordinates
r = np.sqrt(x**2 + y**2)  # distance r 계산
theta = np.arctan2(y, x)  # theta 계산

# 극좌표 결과를 행렬로 표현
polar_coords = np.column_stack((r, theta))
print("극좌표:\n", polar_coords)

극좌표:
 [[0.86266072 1.52553774]
 [0.68205047 1.21698237]
 [0.05184737 0.60798638]
 [0.83169923 1.55411483]
 [0.79819748 0.56826957]
 [0.5860208  0.83873665]
 [0.89613269 0.7121786 ]
 [0.60189558 0.21026932]
 [1.33097883 0.74268207]
 [0.91518632 1.05655199]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [65]:
Z = np.random.uniform(1, 10, size=10)
Z [Z.argmax()] = 0
print(Z)

[9.25649334 8.08417334 6.32135157 6.90771839 4.02764295 7.9583377
 0.         3.02246531 9.22371947 3.93623517]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [72]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distance = abs(v-Z)
np.argmin(distance)

29

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [79]:
Z = np.arange(9).reshape(3,3)
for index, x in np.ndenumerate(Z):
    print(index, x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [85]:
n = 10 #임의로 설정
p = 10 #임의로 설정
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False), 5)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 5. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 5.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 5. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [98]:
Z = np.random.randint(0,10,(3,3))
print(Z)

# column 1
indexes = np.argsort(Z[:, 0])
print(Z[indexes])

[[9 5 9]
 [1 3 9]
 [6 9 2]]
[[1 3 9]
 [6 9 2]
 [9 5 9]]


In [99]:
# column 2
indexes = np.argsort(Z[:, 1])
print(Z[indexes])

[[1 3 9]
 [9 5 9]
 [6 9 2]]


In [100]:
# column 3
indexes = np.argsort(Z[:, 2])
print(Z[indexes])

[[6 9 2]
 [9 5 9]
 [1 3 9]]
